### ISSUE TITLE
Yongey Mingyur Rinpoche can view the Leaderboard of all the people using the app

### ISSUE THREAD

**Issue by DepartureLV** [DepartureLV/brushing-encouragement-web-app#1]

**Comment by dominiksakic** [comment]
Yongey Mingyur Rinpoche when he logs into the app, he can see a Leaderboard of all the users on the right side.
The leaderboard updates when he finished brushing his theeth.

**Comment by DepartureLV** [comment]
[Leaderboard endpoint #9](https://github.com/DepartureLV/brushing-encouragement-web-app/pull/9)
Server already prepare the endpoint for client side to use
fetch through this endpoint: ```/leaderboard```

**Comment by DepartureLV** [comment]
The client can fetch successfully. Issue closed. For styling, please open new issue
