### ISSUE TITLE
Yongey Mingyur Rinpoche can login via a verification System

### ISSUE THREAD

**Issue by dominiksakic** [DepartureLV/brushing-encouragement-web-app#2]

**Comment by dominiksakic** [comment]
When Yongey Mingyur Rinpoche logs in he has to use his password.
His information is stored safe in the back end so that he dosent have to worry and can continue brushing his teeth.

**Comment by DepartureLV** [comment]
https://github.com/DepartureLV/brushing-encouragement-web-app/pull/11

Establish the endpoint name ```/user/login``` for login.

If the login was successful, get the token and message.
If it fails, get a message.

**Comment by DepartureLV** [comment]
@dominiksakic need UI for client side

**Comment by DepartureLV** [comment]
https://github.com/DepartureLV/brushing-encouragement-web-app/pull/31

simple UI complete with signup feature.
