### ISSUE TITLE
Yongey Mingyur Rinpoche can click the floss button after brushing his theeth to gain extra stars

### ISSUE THREAD

**Issue by dominiksakic** [DepartureLV/brushing-encouragement-web-app#3]

**Comment by dominiksakic** [comment]
Yongey Mingyur Rinpoche can brush gain extra points and the high ground over other users if he flosses after he brushes his theeth.
The leaderboard should reflect it soon afterwards.

@DepartureLV please make the database migrations for this feature

**Comment by DepartureLV** [comment]
The endpoint is now established.

use ```/starScore/flossy/:id``` to access it.

**Comment by DepartureLV** [comment]
https://github.com/DepartureLV/brushing-encouragement-web-app/pull/32 UI created. Users can now interact properly.
